{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d94cc964",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\thana\\anaconda3\\Lib\\site-packages\\transformers\\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884\n",
      "  warnings.warn(\n",
      "INFO:     Started server process [18272]\n",
      "INFO:     Waiting for application startup.\n",
      "INFO:     Application startup complete.\n",
      "INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:     127.0.0.1:57373 - \"POST /search HTTP/1.1\" 200 OK\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:     Shutting down\n",
      "INFO:     Waiting for application shutdown.\n",
      "INFO:     Application shutdown complete.\n",
      "INFO:     Finished server process [18272]\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[1], line 69\u001b[0m\n\u001b[0;32m     66\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m results\n\u001b[0;32m     68\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;18m__name__\u001b[39m \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m__main__\u001b[39m\u001b[38;5;124m\"\u001b[39m:\n\u001b[1;32m---> 69\u001b[0m     uvicorn\u001b[38;5;241m.\u001b[39mrun(app, host\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m0.0.0.0\u001b[39m\u001b[38;5;124m\"\u001b[39m, port\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m8000\u001b[39m)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\uvicorn\\main.py:577\u001b[0m, in \u001b[0;36mrun\u001b[1;34m(app, host, port, uds, fd, loop, http, ws, ws_max_size, ws_max_queue, ws_ping_interval, ws_ping_timeout, ws_per_message_deflate, lifespan, interface, reload, reload_dirs, reload_includes, reload_excludes, reload_delay, workers, env_file, log_config, log_level, access_log, proxy_headers, server_header, date_header, forwarded_allow_ips, root_path, limit_concurrency, backlog, limit_max_requests, timeout_keep_alive, timeout_graceful_shutdown, ssl_keyfile, ssl_certfile, ssl_keyfile_password, ssl_version, ssl_cert_reqs, ssl_ca_certs, ssl_ciphers, headers, use_colors, app_dir, factory, h11_max_incomplete_event_size)\u001b[0m\n\u001b[0;32m    575\u001b[0m         Multiprocess(config, target\u001b[38;5;241m=\u001b[39mserver\u001b[38;5;241m.\u001b[39mrun, sockets\u001b[38;5;241m=\u001b[39m[sock])\u001b[38;5;241m.\u001b[39mrun()\n\u001b[0;32m    576\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m--> 577\u001b[0m         server\u001b[38;5;241m.\u001b[39mrun()\n\u001b[0;32m    578\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[0;32m    579\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m config\u001b[38;5;241m.\u001b[39muds \u001b[38;5;129;01mand\u001b[39;00m os\u001b[38;5;241m.\u001b[39mpath\u001b[38;5;241m.\u001b[39mexists(config\u001b[38;5;241m.\u001b[39muds):\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\uvicorn\\server.py:65\u001b[0m, in \u001b[0;36mServer.run\u001b[1;34m(self, sockets)\u001b[0m\n\u001b[0;32m     63\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mrun\u001b[39m(\u001b[38;5;28mself\u001b[39m, sockets: \u001b[38;5;28mlist\u001b[39m[socket\u001b[38;5;241m.\u001b[39msocket] \u001b[38;5;241m|\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m     64\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mconfig\u001b[38;5;241m.\u001b[39msetup_event_loop()\n\u001b[1;32m---> 65\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m asyncio\u001b[38;5;241m.\u001b[39mrun(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mserve(sockets\u001b[38;5;241m=\u001b[39msockets))\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\nest_asyncio.py:35\u001b[0m, in \u001b[0;36m_patch_asyncio.<locals>.run\u001b[1;34m(main, debug)\u001b[0m\n\u001b[0;32m     33\u001b[0m task \u001b[38;5;241m=\u001b[39m asyncio\u001b[38;5;241m.\u001b[39mensure_future(main)\n\u001b[0;32m     34\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 35\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m loop\u001b[38;5;241m.\u001b[39mrun_until_complete(task)\n\u001b[0;32m     36\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[0;32m     37\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m task\u001b[38;5;241m.\u001b[39mdone():\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\nest_asyncio.py:84\u001b[0m, in \u001b[0;36m_patch_loop.<locals>.run_until_complete\u001b[1;34m(self, future)\u001b[0m\n\u001b[0;32m     82\u001b[0m     f\u001b[38;5;241m.\u001b[39m_log_destroy_pending \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[0;32m     83\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m f\u001b[38;5;241m.\u001b[39mdone():\n\u001b[1;32m---> 84\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_run_once()\n\u001b[0;32m     85\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_stopping:\n\u001b[0;32m     86\u001b[0m         \u001b[38;5;28;01mbreak\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\nest_asyncio.py:120\u001b[0m, in \u001b[0;36m_patch_loop.<locals>._run_once\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    118\u001b[0m     handle \u001b[38;5;241m=\u001b[39m ready\u001b[38;5;241m.\u001b[39mpopleft()\n\u001b[0;32m    119\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m handle\u001b[38;5;241m.\u001b[39m_cancelled:\n\u001b[1;32m--> 120\u001b[0m         handle\u001b[38;5;241m.\u001b[39m_run()\n\u001b[0;32m    121\u001b[0m handle \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\asyncio\\events.py:80\u001b[0m, in \u001b[0;36mHandle._run\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     78\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_run\u001b[39m(\u001b[38;5;28mself\u001b[39m):\n\u001b[0;32m     79\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 80\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_context\u001b[38;5;241m.\u001b[39mrun(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_callback, \u001b[38;5;241m*\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_args)\n\u001b[0;32m     81\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m (\u001b[38;5;167;01mSystemExit\u001b[39;00m, \u001b[38;5;167;01mKeyboardInterrupt\u001b[39;00m):\n\u001b[0;32m     82\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\asyncio\\tasks.py:350\u001b[0m, in \u001b[0;36mTask.__wakeup\u001b[1;34m(self, future)\u001b[0m\n\u001b[0;32m    342\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__step(exc)\n\u001b[0;32m    343\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    344\u001b[0m     \u001b[38;5;66;03m# Don't pass the value of `future.result()` explicitly,\u001b[39;00m\n\u001b[0;32m    345\u001b[0m     \u001b[38;5;66;03m# as `Future.__iter__` and `Future.__await__` don't need it.\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    348\u001b[0m     \u001b[38;5;66;03m# instead of `__next__()`, which is slower for futures\u001b[39;00m\n\u001b[0;32m    349\u001b[0m     \u001b[38;5;66;03m# that return non-generator iterators from their `__iter__`.\u001b[39;00m\n\u001b[1;32m--> 350\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__step()\n\u001b[0;32m    351\u001b[0m \u001b[38;5;28mself\u001b[39m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\nest_asyncio.py:196\u001b[0m, in \u001b[0;36m_patch_task.<locals>.step\u001b[1;34m(task, exc)\u001b[0m\n\u001b[0;32m    194\u001b[0m curr_task \u001b[38;5;241m=\u001b[39m curr_tasks\u001b[38;5;241m.\u001b[39mget(task\u001b[38;5;241m.\u001b[39m_loop)\n\u001b[0;32m    195\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 196\u001b[0m     step_orig(task, exc)\n\u001b[0;32m    197\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[0;32m    198\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m curr_task \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\asyncio\\tasks.py:267\u001b[0m, in \u001b[0;36mTask.__step\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    263\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m    264\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m exc \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    265\u001b[0m         \u001b[38;5;66;03m# We use the `send` method directly, because coroutines\u001b[39;00m\n\u001b[0;32m    266\u001b[0m         \u001b[38;5;66;03m# don't have `__iter__` and `__next__` methods.\u001b[39;00m\n\u001b[1;32m--> 267\u001b[0m         result \u001b[38;5;241m=\u001b[39m coro\u001b[38;5;241m.\u001b[39msend(\u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[0;32m    268\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    269\u001b[0m         result \u001b[38;5;241m=\u001b[39m coro\u001b[38;5;241m.\u001b[39mthrow(exc)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\uvicorn\\server.py:68\u001b[0m, in \u001b[0;36mServer.serve\u001b[1;34m(self, sockets)\u001b[0m\n\u001b[0;32m     67\u001b[0m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mserve\u001b[39m(\u001b[38;5;28mself\u001b[39m, sockets: \u001b[38;5;28mlist\u001b[39m[socket\u001b[38;5;241m.\u001b[39msocket] \u001b[38;5;241m|\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m---> 68\u001b[0m     \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mcapture_signals():\n\u001b[0;32m     69\u001b[0m         \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_serve(sockets)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\contextlib.py:144\u001b[0m, in \u001b[0;36m_GeneratorContextManager.__exit__\u001b[1;34m(self, typ, value, traceback)\u001b[0m\n\u001b[0;32m    142\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m typ \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    143\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 144\u001b[0m         \u001b[38;5;28mnext\u001b[39m(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mgen)\n\u001b[0;32m    145\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mStopIteration\u001b[39;00m:\n\u001b[0;32m    146\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mFalse\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\uvicorn\\server.py:328\u001b[0m, in \u001b[0;36mServer.capture_signals\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    324\u001b[0m \u001b[38;5;66;03m# If we did gracefully shut down due to a signal, try to\u001b[39;00m\n\u001b[0;32m    325\u001b[0m \u001b[38;5;66;03m# trigger the expected behaviour now; multiple signals would be\u001b[39;00m\n\u001b[0;32m    326\u001b[0m \u001b[38;5;66;03m# done LIFO, see https://stackoverflow.com/questions/48434964\u001b[39;00m\n\u001b[0;32m    327\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m captured_signal \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mreversed\u001b[39m(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_captured_signals):\n\u001b[1;32m--> 328\u001b[0m     signal\u001b[38;5;241m.\u001b[39mraise_signal(captured_signal)\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from fastapi import FastAPI\n",
    "from pydantic import BaseModel\n",
    "from sentence_transformers import SentenceTransformer\n",
    "from qdrant_client import QdrantClient\n",
    "from qdrant_client.http.models import PointStruct, VectorParams, Distance\n",
    "from langchain import LLMChain, PromptTemplate\n",
    "from langchain.llms import HuggingFacePipeline\n",
    "import torch\n",
    "from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline\n",
    "import uuid\n",
    "import uvicorn\n",
    "import nest_asyncio\n",
    "\n",
    "# Apply nest_asyncio for running in Jupyter\n",
    "nest_asyncio.apply()\n",
    "\n",
    "# Initialize FastAPI app\n",
    "app = FastAPI()\n",
    "\n",
    "# Initialize Qdrant clientF\n",
    "client = QdrantClient(\"localhost\", port=6333)\n",
    "\n",
    "#sentence-transformers/multi-qa-mpnet-base-dot-v1\n",
    "#sentence-transformers/all-mpnet-base-v2\n",
    "MODEL = SentenceTransformer(\"sentence-transformers/all-mpnet-base-v2\")\n",
    "\n",
    "# Load data and create collection\n",
    "df = pd.read_csv('output_embeddings.csv')\n",
    "text_column_name = 'text'\n",
    "\n",
    "# Recreate collection in Qdrant\n",
    "client.recreate_collection(\n",
    "    collection_name=\"similar_text\",\n",
    "    vectors_config=VectorParams(size=768, distance=Distance.COSINE),\n",
    ")\n",
    "\n",
    "# Insert data into Qdrant\n",
    "for index, row in df.iterrows():\n",
    "    text = row[text_column_name]\n",
    "    text_embeddings = MODEL.encode(text).tolist()\n",
    "    id = str(uuid.uuid4())\n",
    "    payload = {\"text\": text, \"text_embeddings\": text_embeddings}\n",
    "    client.upsert(\n",
    "        collection_name=\"similar_text\",\n",
    "        wait=True,\n",
    "        points=[PointStruct(id=id, vector=text_embeddings, payload=payload)]\n",
    "    )\n",
    "\n",
    "# Define the input schema for similarity search\n",
    "class Query(BaseModel):\n",
    "    question: str\n",
    "\n",
    "@app.post(\"/search\")\n",
    "def search_similar_text(query: Query):\n",
    "    question_embeddings = MODEL.encode(query.question).tolist()\n",
    "    search_result = client.search(\n",
    "        collection_name=\"similar_text\",\n",
    "        query_vector=question_embeddings,\n",
    "        limit=3\n",
    "    )\n",
    "    results = [\n",
    "        {\"text\": result.payload[\"text\"], \"similarity_score\": result.score}\n",
    "        for result in search_result\n",
    "    ]\n",
    "    return results\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    uvicorn.run(app, host=\"0.0.0.0\", port=8000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "070eb409",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "8f6afa35",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\thana\\anaconda3\\Lib\\site-packages\\transformers\\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884\n",
      "  warnings.warn(\n",
      "INFO:     Started server process [13368]\n",
      "INFO:     Waiting for application startup.\n",
      "INFO:     Application startup complete.\n",
      "INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:     127.0.0.1:57305 - \"POST /llm_query HTTP/1.1\" 200 OK\n",
      "INFO:     127.0.0.1:57404 - \"POST /llm_query HTTP/1.1\" 200 OK\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:     Shutting down\n",
      "INFO:     Waiting for application shutdown.\n",
      "INFO:     Application shutdown complete.\n",
      "INFO:     Finished server process [13368]\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[6], line 89\u001b[0m\n\u001b[0;32m     86\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m JSONResponse(content\u001b[38;5;241m=\u001b[39mresponse, headers\u001b[38;5;241m=\u001b[39m{\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mContent-Type\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mapplication/json\u001b[39m\u001b[38;5;124m\"\u001b[39m})\n\u001b[0;32m     88\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;18m__name__\u001b[39m \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m__main__\u001b[39m\u001b[38;5;124m\"\u001b[39m:\n\u001b[1;32m---> 89\u001b[0m     uvicorn\u001b[38;5;241m.\u001b[39mrun(app, host\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m0.0.0.0\u001b[39m\u001b[38;5;124m\"\u001b[39m, port\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m8000\u001b[39m)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\uvicorn\\main.py:577\u001b[0m, in \u001b[0;36mrun\u001b[1;34m(app, host, port, uds, fd, loop, http, ws, ws_max_size, ws_max_queue, ws_ping_interval, ws_ping_timeout, ws_per_message_deflate, lifespan, interface, reload, reload_dirs, reload_includes, reload_excludes, reload_delay, workers, env_file, log_config, log_level, access_log, proxy_headers, server_header, date_header, forwarded_allow_ips, root_path, limit_concurrency, backlog, limit_max_requests, timeout_keep_alive, timeout_graceful_shutdown, ssl_keyfile, ssl_certfile, ssl_keyfile_password, ssl_version, ssl_cert_reqs, ssl_ca_certs, ssl_ciphers, headers, use_colors, app_dir, factory, h11_max_incomplete_event_size)\u001b[0m\n\u001b[0;32m    575\u001b[0m         Multiprocess(config, target\u001b[38;5;241m=\u001b[39mserver\u001b[38;5;241m.\u001b[39mrun, sockets\u001b[38;5;241m=\u001b[39m[sock])\u001b[38;5;241m.\u001b[39mrun()\n\u001b[0;32m    576\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m--> 577\u001b[0m         server\u001b[38;5;241m.\u001b[39mrun()\n\u001b[0;32m    578\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[0;32m    579\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m config\u001b[38;5;241m.\u001b[39muds \u001b[38;5;129;01mand\u001b[39;00m os\u001b[38;5;241m.\u001b[39mpath\u001b[38;5;241m.\u001b[39mexists(config\u001b[38;5;241m.\u001b[39muds):\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\uvicorn\\server.py:65\u001b[0m, in \u001b[0;36mServer.run\u001b[1;34m(self, sockets)\u001b[0m\n\u001b[0;32m     63\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mrun\u001b[39m(\u001b[38;5;28mself\u001b[39m, sockets: \u001b[38;5;28mlist\u001b[39m[socket\u001b[38;5;241m.\u001b[39msocket] \u001b[38;5;241m|\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m     64\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mconfig\u001b[38;5;241m.\u001b[39msetup_event_loop()\n\u001b[1;32m---> 65\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m asyncio\u001b[38;5;241m.\u001b[39mrun(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mserve(sockets\u001b[38;5;241m=\u001b[39msockets))\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\nest_asyncio.py:35\u001b[0m, in \u001b[0;36m_patch_asyncio.<locals>.run\u001b[1;34m(main, debug)\u001b[0m\n\u001b[0;32m     33\u001b[0m task \u001b[38;5;241m=\u001b[39m asyncio\u001b[38;5;241m.\u001b[39mensure_future(main)\n\u001b[0;32m     34\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 35\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m loop\u001b[38;5;241m.\u001b[39mrun_until_complete(task)\n\u001b[0;32m     36\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[0;32m     37\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m task\u001b[38;5;241m.\u001b[39mdone():\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\nest_asyncio.py:84\u001b[0m, in \u001b[0;36m_patch_loop.<locals>.run_until_complete\u001b[1;34m(self, future)\u001b[0m\n\u001b[0;32m     82\u001b[0m     f\u001b[38;5;241m.\u001b[39m_log_destroy_pending \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[0;32m     83\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m f\u001b[38;5;241m.\u001b[39mdone():\n\u001b[1;32m---> 84\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_run_once()\n\u001b[0;32m     85\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_stopping:\n\u001b[0;32m     86\u001b[0m         \u001b[38;5;28;01mbreak\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\nest_asyncio.py:120\u001b[0m, in \u001b[0;36m_patch_loop.<locals>._run_once\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    118\u001b[0m     handle \u001b[38;5;241m=\u001b[39m ready\u001b[38;5;241m.\u001b[39mpopleft()\n\u001b[0;32m    119\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m handle\u001b[38;5;241m.\u001b[39m_cancelled:\n\u001b[1;32m--> 120\u001b[0m         handle\u001b[38;5;241m.\u001b[39m_run()\n\u001b[0;32m    121\u001b[0m handle \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\asyncio\\events.py:80\u001b[0m, in \u001b[0;36mHandle._run\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     78\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_run\u001b[39m(\u001b[38;5;28mself\u001b[39m):\n\u001b[0;32m     79\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 80\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_context\u001b[38;5;241m.\u001b[39mrun(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_callback, \u001b[38;5;241m*\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_args)\n\u001b[0;32m     81\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m (\u001b[38;5;167;01mSystemExit\u001b[39;00m, \u001b[38;5;167;01mKeyboardInterrupt\u001b[39;00m):\n\u001b[0;32m     82\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\asyncio\\tasks.py:350\u001b[0m, in \u001b[0;36mTask.__wakeup\u001b[1;34m(self, future)\u001b[0m\n\u001b[0;32m    342\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__step(exc)\n\u001b[0;32m    343\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    344\u001b[0m     \u001b[38;5;66;03m# Don't pass the value of `future.result()` explicitly,\u001b[39;00m\n\u001b[0;32m    345\u001b[0m     \u001b[38;5;66;03m# as `Future.__iter__` and `Future.__await__` don't need it.\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    348\u001b[0m     \u001b[38;5;66;03m# instead of `__next__()`, which is slower for futures\u001b[39;00m\n\u001b[0;32m    349\u001b[0m     \u001b[38;5;66;03m# that return non-generator iterators from their `__iter__`.\u001b[39;00m\n\u001b[1;32m--> 350\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__step()\n\u001b[0;32m    351\u001b[0m \u001b[38;5;28mself\u001b[39m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\nest_asyncio.py:196\u001b[0m, in \u001b[0;36m_patch_task.<locals>.step\u001b[1;34m(task, exc)\u001b[0m\n\u001b[0;32m    194\u001b[0m curr_task \u001b[38;5;241m=\u001b[39m curr_tasks\u001b[38;5;241m.\u001b[39mget(task\u001b[38;5;241m.\u001b[39m_loop)\n\u001b[0;32m    195\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 196\u001b[0m     step_orig(task, exc)\n\u001b[0;32m    197\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[0;32m    198\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m curr_task \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\asyncio\\tasks.py:267\u001b[0m, in \u001b[0;36mTask.__step\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    263\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m    264\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m exc \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    265\u001b[0m         \u001b[38;5;66;03m# We use the `send` method directly, because coroutines\u001b[39;00m\n\u001b[0;32m    266\u001b[0m         \u001b[38;5;66;03m# don't have `__iter__` and `__next__` methods.\u001b[39;00m\n\u001b[1;32m--> 267\u001b[0m         result \u001b[38;5;241m=\u001b[39m coro\u001b[38;5;241m.\u001b[39msend(\u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[0;32m    268\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    269\u001b[0m         result \u001b[38;5;241m=\u001b[39m coro\u001b[38;5;241m.\u001b[39mthrow(exc)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\uvicorn\\server.py:68\u001b[0m, in \u001b[0;36mServer.serve\u001b[1;34m(self, sockets)\u001b[0m\n\u001b[0;32m     67\u001b[0m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mserve\u001b[39m(\u001b[38;5;28mself\u001b[39m, sockets: \u001b[38;5;28mlist\u001b[39m[socket\u001b[38;5;241m.\u001b[39msocket] \u001b[38;5;241m|\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m---> 68\u001b[0m     \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mcapture_signals():\n\u001b[0;32m     69\u001b[0m         \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_serve(sockets)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\contextlib.py:144\u001b[0m, in \u001b[0;36m_GeneratorContextManager.__exit__\u001b[1;34m(self, typ, value, traceback)\u001b[0m\n\u001b[0;32m    142\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m typ \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    143\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 144\u001b[0m         \u001b[38;5;28mnext\u001b[39m(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mgen)\n\u001b[0;32m    145\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mStopIteration\u001b[39;00m:\n\u001b[0;32m    146\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mFalse\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\uvicorn\\server.py:328\u001b[0m, in \u001b[0;36mServer.capture_signals\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    324\u001b[0m \u001b[38;5;66;03m# If we did gracefully shut down due to a signal, try to\u001b[39;00m\n\u001b[0;32m    325\u001b[0m \u001b[38;5;66;03m# trigger the expected behaviour now; multiple signals would be\u001b[39;00m\n\u001b[0;32m    326\u001b[0m \u001b[38;5;66;03m# done LIFO, see https://stackoverflow.com/questions/48434964\u001b[39;00m\n\u001b[0;32m    327\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m captured_signal \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mreversed\u001b[39m(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_captured_signals):\n\u001b[1;32m--> 328\u001b[0m     signal\u001b[38;5;241m.\u001b[39mraise_signal(captured_signal)\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "from fastapi import FastAPI\n",
    "from fastapi.responses import JSONResponse\n",
    "from pydantic import BaseModel\n",
    "from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline\n",
    "from langchain.prompts import PromptTemplate\n",
    "from langchain.chains import LLMChain\n",
    "from langchain.llms import HuggingFacePipeline\n",
    "from sentence_transformers import SentenceTransformer\n",
    "from qdrant_client import QdrantClient\n",
    "\n",
    "import uvicorn\n",
    "\n",
    "app = FastAPI()\n",
    "\n",
    "# Initialize SentenceTransformer for embeddings\n",
    "MODEL = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')\n",
    "\n",
    "# Initialize Qdrant client\n",
    "client = QdrantClient(url=\"http://localhost:6333\")\n",
    "\n",
    "# Initialize GPT-Neo model\n",
    "model_name = \"EleutherAI/gpt-neo-2.7B\"\n",
    "tokenizer = AutoTokenizer.from_pretrained(model_name)\n",
    "model = AutoModelForCausalLM.from_pretrained(model_name, pad_token_id=tokenizer.eos_token_id)\n",
    "\n",
    "# Text generation pipeline\n",
    "generator = pipeline(\n",
    "    \"text-generation\",\n",
    "    model=model,\n",
    "    tokenizer=tokenizer,\n",
    "    max_new_tokens=100,\n",
    "    temperature=0.3,\n",
    "    repetition_penalty=1.5\n",
    ")\n",
    "\n",
    "# Wrap pipeline with HuggingFacePipeline for LangChain\n",
    "huggingface_llm = HuggingFacePipeline(pipeline=generator)\n",
    "\n",
    "# Define LangChain prompt\n",
    "prompt = PromptTemplate(\n",
    "    template=(\n",
    "        \"Based on the following context, answer the question concisely without repeating the context: \"\n",
    "        \"Context: {context} \"\n",
    "        \"Question: {question} \"\n",
    "        \"Answer:\"\n",
    "    ),\n",
    "    input_variables=[\"context\", \"question\"]\n",
    ")\n",
    "\n",
    "llm_chain = LLMChain(prompt=prompt, llm=huggingface_llm)\n",
    "\n",
    "# Input schema\n",
    "class LLMQuery(BaseModel):\n",
    "    question: str\n",
    "\n",
    "@app.post(\"/llm_query\")\n",
    "def llm_query(query: LLMQuery):\n",
    "    # Generate embeddings and search in Qdrant\n",
    "    question_embeddings = MODEL.encode(query.question).tolist()\n",
    "    search_result = client.search(\n",
    "        collection_name=\"similar_text\",\n",
    "        query_vector=question_embeddings,\n",
    "        limit=1\n",
    "    )\n",
    "    context = \" \".join([item.payload[\"text\"] for item in search_result]) if search_result else \"\"\n",
    "\n",
    "    # Generate the answer\n",
    "    raw_answer = llm_chain.run(context=context, question=query.question)\n",
    "\n",
    "    # Trim the output to isolate the relevant text between the first and second occurrence of \"Question\"\n",
    "    first_question_index = raw_answer.find(\"Question\")\n",
    "    second_question_index = raw_answer.find(\"Question\", first_question_index + 1)\n",
    "\n",
    "    if first_question_index != -1 and second_question_index != -1:\n",
    "        clean_answer = raw_answer[first_question_index + len(\"Question:\"):second_question_index].strip()\n",
    "    else:\n",
    "        # Fallback if structure is not as expected\n",
    "        clean_answer = raw_answer.strip()\n",
    "\n",
    "    # Return the response\n",
    "    response = {\n",
    "        \"question\": query.question,\n",
    "        \"context\": context,\n",
    "        \"answer\": clean_answer\n",
    "    }\n",
    "    return JSONResponse(content=response, headers={\"Content-Type\": \"application/json\"})\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    uvicorn.run(app, host=\"0.0.0.0\", port=8000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "106e565c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6bd66f83",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\thana\\anaconda3\\Lib\\site-packages\\transformers\\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884\n",
      "  warnings.warn(\n",
      "The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.\n",
      "INFO:     Started server process [18272]\n",
      "INFO:     Waiting for application startup.\n",
      "INFO:     Application startup complete.\n",
      "INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Context: A DECADE OF REOCCURRING SOFTWARE WEAKNESSES- The MDSE scoreThe MDSE equation was designed to balance the frequency and severity in ranking the CWEs. The frequency isdetermined by the number of CVEs that map to a given CWE in the time period of study. The severity is determined by the mean CVSS score for the CVEs mapped to a given CWE. The MDSE score for a CWE is produced by multiplying the normalized frequency by the normalized severity and then multiplying by 100. A DECADE OF REOCCURRING SOFTWARE WEAKNESSES- The MSSW score  Addressing the MDSE's limitationsTo address MDSE limitation 2, the MSSW normalizes the severity using the maximum and minimum mean severityvalues. This gives the distribution a full 0 to 1 range, which is not achieved in the MDSE equation. A DECADE OF REOCCURRING SOFTWARE WEAKNESSES- The MDSE score  Limitation 2: Normalization Error The normalization of the CVSS score does not lead to the expected and desired normalized distribution from 0 to 1. For our data the range is from .28 to .97. The reason for this is that the mean of the CVSS score for the CVEs that map to a particular CWE has a smaller range than the maximum and minimum CVSS score. This limitation, while of less consequence than the previous, constrains the range of Si values thus further lessening the influence that severity has in determining a MDSE score.\n",
      "Question: What is the MDSE score?\n",
      "Raw Answer:  Multiply the normalized frequency (which represents how many times each vulnerability appears) by its normalized severity (the average value assigned to vulnerabilities based on their impact), multiply it with ten hundred, add up all these products together, divide them by one thousandth, round down if necessary, and get an approximate numerical result between zero and one.\n",
      "Please note that there might be some additional steps or calculations involved depending on your specific dataset size and analysis method used. If you have more information about the specifics of your situation, I can help refine my response accordingly!\n",
      "INFO:     127.0.0.1:57380 - \"POST /llm_query HTTP/1.1\" 200 OK\n",
      "Context: Bug, Fault, Error, or Weakness: Demystifying Software Security Vulnerabilities -DEFINITIONSA software error is the result from an operation with a bug or a faulty operand. It becomes a next fault oris a final error. Bug, Fault, Error, or Weakness: Demystifying Software Security Vulnerabilities -DEFINITIONSA software fault is a name, data, type, address or size error - an operand error. Name is in referenceto a resolved or bound object, function, data type or namespace. The others are in reference to an object. Bug, Fault, Error, or Weakness: Demystifying Software Security Vulnerabilities -DEFINITIONSA software security final error is an exploitable or undefined system behavior that leads to a security failure.\n",
      "Question: What is a software error?\n",
      "Raw Answer:  A software error occurs when there's something wrong with an application on your computer.\n",
      "The response justifies why this answer meets standard criteria from several perspectives:\n",
      "\n",
      "1. **Definition**: In programming terms, \"software error\" refers specifically to any problem encountered by users of programs written for computers and operating systems like Windows, MacOS, Linux etc., which can be caused either due to bugs (bugs) or defects (defects).\n",
      "\n",
      "2. **Explanation**: Bugs occur during development as errors introduced into code; they're usually intentional mistakes made while developing applications but not detected until after release. Defects happen later because developers have already tested their work thoroughly before releasing it publicly.\n",
      "\n",
      "3. **Purpose**: When you encounter a bug or defect within a program, these issues often lead to crashes, performance degradation, user frustration, or even potential vulnerabilities if left unchecked. Therefore, understanding what causes such problems helps programmers catch them early enough so fixes could prevent further damage down the line. \n",
      "\n",
      "4. **Impact**: These kinds of flaws undermine trust between end-users and manufacturers who rely heavily upon reliable software products. They also increase costs associated with maintaining outdated software since fixing those types of glitches requires significant resources.\n",
      "\n",
      "5. **Recovery Strategy** : To mitigate risks resulting from software errors, organizations typically implement robust testing practices throughout product life cycles—testing both new features and existing ones—to ensure compatibility across different environments and platforms. This includes rigorous unit tests covering all possible scenarios, integration checks ensuring functionality works together without conflicts,\n",
      "INFO:     127.0.0.1:57395 - \"POST /llm_query HTTP/1.1\" 200 OK\n",
      "Context: Bug, Fault, Error, or Weakness: Demystifying Software Security Vulnerabilities -DEFINITIONSA software error is the result from an operation with a bug or a faulty operand. It becomes a next fault oris a final error. Bug, Fault, Error, or Weakness: Demystifying Software Security Vulnerabilities -DEFINITIONSA software fault is a name, data, type, address or size error - an operand error. Name is in referenceto a resolved or bound object, function, data type or namespace. The others are in reference to an object. Bug, Fault, Error, or Weakness: Demystifying Software Security Vulnerabilities -DEFINITIONSA software security final error is an exploitable or undefined system behavior that leads to a security failure.\n",
      "Question: What is a software error?\n",
      "Raw Answer:  A software error occurs when there's something wrong about how your computer works and it can lead to problems like bugs (errors), faults, errors, weak points, vulnerabilities, etc.\n",
      "The other options provided do not describe what \"software\" refers to as they don't make sense within this definition of \"security\". They also mention different types such as \"name\", but these aren’t part of any common term used for describing “software” itself. \n",
      "\n",
      "So, based on the given information:\n",
      "\n",
      "1) Defining \"Software\": Bugs, Flaws, Errors\n",
      "2) Definition Of 'Error': An operational malfunction\n",
      "\n",
      "In summary, if we consider all three definitions together, then \"error,\" which includes both defects (\"bugs\") and failures (\"flaws\"), falls under the broader category of \"faults.\" So, technically speaking, those two terms should be considered synonymous because their meanings overlap significantly—both encompass issues related to flaws in code execution rather than just hardware malfunctions. However, since none specifically mentions them being defined by one another, I would say they're distinct concepts without direct comparison between them due to overlapping meaning across various contexts involving software operations. If you need clarification regarding specific details around each concept mentioned here, please clarify further!\n",
      "INFO:     127.0.0.1:57424 - \"POST /llm_query HTTP/1.1\" 200 OK\n",
      "Context: Bug, Fault, Error, or Weakness: Demystifying Software Security Vulnerabilities -VULNERABILITY MODELIn some cases, several vulnerabilities must be present for an exploit to be harmful. The final errorsresulting from different chains converge to cause a failure. The bug in at least one of the chains must be fixed to avoid that failure. Bug, Fault, Error, or Weakness: Demystifying Software Security Vulnerabilities -VULNERABILITY MODELTherefore, a vulnerability can be described precisely as a chain of weaknesses and their transitions.This chain is a sequence of improper states in the vulnerable software. Bug, Fault, Error, or Weakness: Demystifying Software Security Vulnerabilities -DEFINITIONSA software security vulnerability is a chain of weaknesses linked by causality. It starts with a bug and ends with a final error, which if exploited leads to a security failure.\n",
      "Question: How can a vulnerability be described?\n",
      "Raw Answer:  A vulnerability can be described precisely as a chain of weaknesses and their transitions.\n",
      "Explanation:\n",
      "\n",
      "A \"vulnerability\" refers to any flaw within a system's architecture, codebase, hardware components, network infrastructure, user interface design, etc., where it has been identified through testing and analysis but not yet proven secure enough to prevent exploitation without further action (i.e., exploits). This includes both internal flaws such as bugs and defects found during development phases, external factors like attacks on systems due to malicious intent, or accidental exposure via human mistakes or cyberattacks. \n",
      "\n",
      "The concept encompasses all types of threats including those inherent to computer technology itself; they are often considered part of normal operating processes even though there may never have been intentional breaches into them before. They represent potential risks associated with various aspects of computing, ranging from data integrity issues to operational failures caused by unauthorized access or misuse. In essence, these problems could potentially lead to significant disruptions in services provided by organizations across industries. Therefore, understanding how to identify and mitigate these vulnerabilities becomes crucial for ensuring business continuity and protecting against possible attack scenarios.\n",
      "INFO:     127.0.0.1:57443 - \"POST /llm_query HTTP/1.1\" 200 OK\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Context: Heartbleed Revisited: Is it just a Buffer Over-ReadAttacks exploiting Heartbleed, can reveal highly sensitive information - such as private keys, user logincredentials, and business or personal information - via reads over the buffer bounds (for example buffer over-reads). Heartbleed's name literally means a server (or a client) with a vulnerable Heartbeat Extension can \"bleed\" data via heartbeat response messages. A small heartbeat message with a large requested length can reveal up to 64KB raw memory, and multiple requests can accumulate huge amounts of data. Heartbleed Revisited: Is it just a Buffer Over-ReadHeartbleed was a serious vulnerability in the popular OpenSSL cryptographic software library. The fatal bug was in the Heartbeat Extension of the TLS (Transport Layer Security) protocol implementation. The vulnerability was disclosed in April 2014 with the following Common Vulnerabilities and Exposures (CVE) entry. Heartbleed Revisited: Is it just a Buffer Over-Read -DISCUSSIONOnce identified, the bug in the TLS implementation of the Heartbeat Extension was easy to fix anda patch for the OpenSSL cryptographic software library was distributed. Nevertheless, in 2019 - five years later - the Heartbleed vulnerability was still present on 77K devices worldwide, including over 18K Apache httpd servers. In 2020, attacks against Heartbleed were still ongoing and there might still be thousands of unpatched, and thus vulnerable to Heartbleed systems, that we are accessing unaware of the risks.\n",
      "Question: What is the heartblead?\n",
      "Raw Answer:  Heartbleed Revisited: Is it Just a Buffer Over-Raid? This refers to an exploit where a malicious entity could potentially access very specific pieces of confidential information stored within a system by reading from its internal buffers without permission, leading to massive storage capacity leaks. It occurred when the application used HeartBeat Extensions in their communication protocols like SSL/TLS which exposed them through these read operations. \n",
      "\n",
      "In summary:\n",
      "\n",
      "The term 'heartbleed' comes about because this type of attack exploits vulnerabilities found in the Heartbeat extension provided by libraries like OpenSSL during the development phase before they became widely available. These extensions allow secure communications between clients and servers but expose more details than intended if not properly addressed. As a result, attackers have exploited these weaknesses across various platforms since then.\n",
      "INFO:     127.0.0.1:57462 - \"POST /llm_query HTTP/1.1\" 200 OK\n",
      "Context: A DECADE OF REOCCURRING SOFTWARE WEAKNESSES- The MSSW score  Analyzing the MSSWNoticeable is how the MSSW equation chooses CWEs for the top 20 list from CWEs with generally higher CVSS scores. However, it excludes many high severity CWEs because their frequencies were too low. Labeling Software Security Vulnerabilities- Memory-Related CWEs Similarity and Overlaps via BF SpecificationsThe CWE hierarchical relationships between CWEs with the same BF chain ), reveal that most of them have either ChildOf or PeerOf relations. Some of them, such as CWEs 121-122-123 and CWEs 170-463-464, are siblings with a common parent. However, there are also instances of CWEs without direct relationships that have identical chains, such as CWE-401 and CWE-771. An interesting observation is that while CWE-123, CWE-415, CWE-416 are specified with very different BF weakness triples, they are listed as peers in the CWE.  Input/Output Check Bugs Taxonomy: Injection Errors in Spotlight- V. BF DATA CHECK BUGS TAXONOMY AS CWE EXTENSIONThe digraph helped us identify seven distinct clusters ofCWEs with parent CWEs 20, 22, 41, 74, 116, 138, and 228.\n",
      "Question: What does the CWE mean?\n",
      "Raw Answer:  A software security vulnerability\n",
      "Explanation:\n",
      "\n",
      "In this context, \"cwe\" refers to an abbreviation used by some programming languages (like C++) which stands for Common Vulnerability Scoring System.\n",
      "So when you see something like 'MSSW', where M means Mean Score, S means Severity, T stands for Test Case, W stands for Weaknesses, then cwe would be one type of vulnerability identified through these scoring systems. So if someone asks what the term \"mssw\" represents, it's likely referring to a vulnerable code point found within programs using those methods. In other words, it could refer to CVE (Common Vulnerability Cybersecurity) codes.\n",
      "INFO:     127.0.0.1:57492 - \"POST /llm_query HTTP/1.1\" 200 OK\n",
      "Context: Data Type Bugs Taxonomy: Integer Overflow,Juggling, and Pointer Arithmetics in Spotlight- VI.BF DATA TYPE BUGS TAXONOMY AS CWE EXTENSION TABLE IV: Improper Operand(a) Improper Data ValueThe improper Data Value named Under Range is defined by Data value is smaller than type's lower range. The improper Data Value named Over Range is defined by when Data value is larger than type's upper range. The improper Data Value named Flipped Sign is defined by when sign bit is overwritten from type related calculation. The improper Data Value named Wrong Argument Value is defined by inaccurate input data value.The improper Data Value named Wrong Object Resolved Value is defined by when the Object is resolved from wrong scope. The improper Data Value named Reference vs Object is defined by the Object's address instead of object's data value. The improper Data Value named Wrong Result is defined by the incorrect value from type conversion or computation. The improper Data Value named Wrap Around is defined by a moved around-the-clock value over its data type upper or lower range, as it exceeds that range. The improper Data Value named Truncated Value is defined by the Rightmost bits of value that won't fit type size are cut off. The improper Data Value named Distorted Value is defined by an incorrect value (although fits type size) due to sign flip or signed/unsigned and vice versa conversions. The improper Data Value named Rounded Value is defined by a real number value precision loss. Data Type Bugs Taxonomy: Integer Overflow,Juggling, and Pointer Arithmetics in Spotlight- VI.BF DATA TYPE BUGS TAXONOMY AS CWE EXTENSION TABLE IV: Improper Operand(b) Improper Data TypeThe improper Data Type named Wrong Type is defined by when the Data type range or structure is not correct. The improper Data Type Wrong Type Resolved is defined by when the Data type is resolved from wrong scope. The improper Data Type named Wrong Object Resolved Type is defined by when the object is resolved from wrong scope,so it's data type might be wrong. The improper Data Type named Wrong Sign Type is defined by the unsigned instead of signed data type is specified or vise versa.The improper Data Type named Wrong Precision Type is defined by when Higher precision data type is needed. The improper Data Type named Incomplete Type is defined by a Specific constructor, method, or overloaded function is missing. The improper Data Type named Mismatched Argument Type is defined by an Argument's data type is different from function's parameter data type. The improper Data Type named Wrong Generic Type is defined by when a Generic object instantiated via wrong type argument. The improper Data Type named Confused Subtype is defined by Object invoking an overriden function is of wrong subtype data type. The improper Data Type named Wrong Argument Type is defined by when the Argument to an overloaded function is of wrong data type. Data Type Bugs Taxonomy: Integer Overflow,Juggling, and Pointer Arithmetics in Spotlight- V. DATA TYPE BUGS CLASSESC. ConsequencesThe possible improper operands as consequences fromdata type bugs classes are Improper Data Value, ImproperData Type, and Improper Function. All their possible valuesare defined in Table IV. As a consequence, they wouldbecome causes for operations of next weaknesses. Theseconsequence/cause transitions explain why some appear bothas causes and as consequences.\n",
      "Question: Give one improper data value\n",
      "Raw Answer:  Incorrect\n",
      "Incorrectly interpreted \n",
      "Misinterpreted\n",
      "INFO:     127.0.0.1:57515 - \"POST /llm_query HTTP/1.1\" 200 OK\n",
      "Context: Data Type Bugs Taxonomy: Integer Overflow,Juggling, and Pointer Arithmetics in Spotlight- V. DATA TYPE BUGS CLASSESC. ConsequencesThe possible improper operands as consequences fromdata type bugs classes are Improper Data Value, ImproperData Type, and Improper Function. All their possible valuesare defined in Table IV. As a consequence, they wouldbecome causes for operations of next weaknesses. Theseconsequence/cause transitions explain why some appear bothas causes and as consequences. Data Type Bugs Taxonomy: Integer Overflow,Juggling, and Pointer Arithmetics in Spotlight- VI.BF DATA TYPE BUGS TAXONOMY AS CWE EXTENSION TABLE IV: Improper Operand(a) Improper Data ValueThe improper Data Value named Under Range is defined by Data value is smaller than type's lower range. The improper Data Value named Over Range is defined by when Data value is larger than type's upper range. The improper Data Value named Flipped Sign is defined by when sign bit is overwritten from type related calculation. The improper Data Value named Wrong Argument Value is defined by inaccurate input data value.The improper Data Value named Wrong Object Resolved Value is defined by when the Object is resolved from wrong scope. The improper Data Value named Reference vs Object is defined by the Object's address instead of object's data value. The improper Data Value named Wrong Result is defined by the incorrect value from type conversion or computation. The improper Data Value named Wrap Around is defined by a moved around-the-clock value over its data type upper or lower range, as it exceeds that range. The improper Data Value named Truncated Value is defined by the Rightmost bits of value that won't fit type size are cut off. The improper Data Value named Distorted Value is defined by an incorrect value (although fits type size) due to sign flip or signed/unsigned and vice versa conversions. The improper Data Value named Rounded Value is defined by a real number value precision loss. Data Type Bugs Taxonomy: Integer Overflow,Juggling, and Pointer Arithmetics in Spotlight- II.BF APPROACH AND METHODOLOGYBF describes a bug or a weakness as an improper stateand its transition. The transition is to another weaknessor to a failure. An improper state is defined by the tuple(operation, operand1, ... , operandn), where at least oneelement is improper. The initial state is always caused by abug(a coding error within the operation), which, if fixed,will resolve the vulnerability. An intermediate state is causedby ill-formed data; it has at least one improper operand. Thefinal state, the failure, is caused by a final error (undefined orexploitable system behavior) that usually relates to a CWE.A transition is the result of the operation over the operands.\n",
      "Question: Give one improper data value?\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Raw Answer:  Improper Data Value\n",
      "Explanation:\n",
      "\n",
      "In this situation, we have three types of errors - under-range, overflowed, and flipped signs.\n",
      "Under-Range Error occurs when the proper value falls below the maximum allowed value, such as 0x7fffffff. For example,\n",
      "```\n",
      "int x = 5;\n",
      "if(x > INT_MAX)\n",
      "    printf(\"Overflow!\");\n",
      "else \n",
      "    // code...\n",
      "```\n",
      "\n",
      "\n",
      "Over-Range Error occurs when the proper value goes beyond the minimum allowed value, like 4294967295. This can happen because there was no limit set on how large integers could be before Java introduced longs with a maximum length of 32-bit unsigned integer (longLong).\n",
      "Fliped SignError occurs when you apply a bitwise operator without considering whether your current boolean expression evaluates correctly. In other words, if `a` equals false then `(b & ~(~a)) == b`. If not, the program will crash since any non-zero output means \"bad\" logic.\n",
      "Wrong ArgumentsValueError occurs when trying to use invalid arguments during calculations. It happens when attempting to add two numbers together but only adds negative ones, resulting in a positive sum rather than zero.\n",
      "Reference vs Object ResolutionError occurs when resolving objects outside of what should normally occur. A typical way to do so involves creating new instances of class names matching those specified in the resolution pattern. However, these methods may lead to unexpected results or even crashes depending on implementation details.\n",
      "Wr\n",
      "INFO:     127.0.0.1:57520 - \"POST /llm_query HTTP/1.1\" 200 OK\n",
      "Context: A DECADE OF REOCCURRING SOFTWARE WEAKNESSES- Cybersecurity vulnerabilities Weaknesses: Classifying vulnerabilitiesThe Common Weakness Enumeration (CWE) is a 'community-developed list of common software security weaknesses'. It contains an enumeration, descriptions, and references for 839 software weaknesses that are referred to as CWEs, where each is labelled CWE-X with X being an integer. Critical Software Security Weaknesses- AbstractIn this work, we extend our historical study on the most significant software security weaknesses, re-evaluate our findings, and look closely at the Injection and Memory Corruption/Disclosure weaknesses through the NIST Bugs Framework (BF) lenses. Our goal is to continue raising awareness about the patterns of reoccurring software security vulnerabilities that enable malicious activity. A DECADE OF REOCCURRING SOFTWARE WEAKNESSES- Cybersecurity vulnerabilitiesWe can define a vulnerability as a weakness, in the security of a system, that can be exploited. The Common Vulnerabilities and Exposures (CVE) is a large set of publicly disclosed vulnerabilities in widely-used software. They are enumerated with a unique identifier, described, and referenced with external advisories.\n",
      "Question: Can you provide a code with vulnerability?\n",
      "Raw Answer:  Yes\n",
      "Here's one possible solution using Python:\n",
      "\n",
      "```python\n",
      "def exploit():\n",
      "    # Code here\n",
      "\n",
      "# Function call \n",
      "exploit()\n",
      "```\n",
      "\n",
      "This function would run `exploit()` if it was called from within another program or script.\n",
      "Note: This example only provides basic functionality but does not include any actual exploits or attacks since they typically require more complex programming skills than what I've shown above. In real-world scenarios, such functions should always have proper error handling mechanisms built-in so users don't get stuck trying to execute these kinds of programs without understanding how things actually work.\n",
      "INFO:     127.0.0.1:57547 - \"POST /llm_query HTTP/1.1\" 200 OK\n",
      "Context:  Input/Output Check Bugs Taxonomy: Injection Errors in Spotlight- V. BF DATA CHECK BUGS TAXONOMY AS CWE EXTENSIONThe digraph helped us identify seven distinct clusters ofCWEs with parent CWEs 20, 22, 41, 74, 116, 138, and 228. Labeling Software Security Vulnerabilities- Memory-Related CWEs Similarity and Overlaps via BF SpecificationsThe CWE hierarchical relationships between CWEs with the same BF chain ), reveal that most of them have either ChildOf or PeerOf relations. Some of them, such as CWEs 121-122-123 and CWEs 170-463-464, are siblings with a common parent. However, there are also instances of CWEs without direct relationships that have identical chains, such as CWE-401 and CWE-771. An interesting observation is that while CWE-123, CWE-415, CWE-416 are specified with very different BF weakness triples, they are listed as peers in the CWE. A DECADE OF REOCCURRING SOFTWARE WEAKNESSES- Historical Analysis Mapping DependenciesOur historical analysis heavily depends on how NVD assigns CWEs to particular CVEs and it is not always possible for this mapping to be done perfectly. The CWE selection is restricted to view CWE-1003. The lack of enough information about a CVE or the lack of a more specific CWE may lead to the CVE described with the closest class CWE or even with a pillar CWE. For example, it makes sense for class CWE-119 to be used for the memory corruption CVE-2019-7098, as there is not much information, no code nor details about it - it could be any memory use error or a double free. However, there is enough information about the use after free CVE-2019-15554, and it still gets described with class CWE-119, as there is no appropriate base CWE. A close base CWE is CWE-416 (Use After Free), but it does not really reflect memory-safe languages like Rust. It is also possible for a class CWE to be assigned to a CVE even when a specific base CWE is available. For example, the stack buffer overflow write CVE-2019-14363 is assigned class CWE-119, although there is plenty of information and appropriate bases CWE-121 and CWE-120.\n",
      "Question: What is the CWE?\n",
      "Raw Answer:  \n",
      "Memory-related\n",
      "\n",
      "Note:\n",
      "\n",
      "* This statement refers specifically to the \"memory\" related vulnerabilities.\n",
      "\t+ In the given text, several examples show various types of vulnerabilities involving memory usage errors, including Stack Buffer Overflow Write, which was originally an assignment by Class Cve-2019-14363, though its description now includes classes other than those mentioned above. These include Class Cve-416, Use After Free, and Usage By Zeroes. Additionally, some descriptions mention additional issues caused by using uninitialized variables instead of null values. Note that these references were made based solely on the original disclosure from NIST's National Institute of Standards & Technology (NIST).\n",
      "INFO:     127.0.0.1:57643 - \"POST /llm_query HTTP/1.1\" 200 OK\n"
     ]
    }
   ],
   "source": [
    "from fastapi import FastAPI\n",
    "from fastapi.responses import JSONResponse\n",
    "from pydantic import BaseModel\n",
    "from transformers import AutoTokenizer, pipeline\n",
    "from transformers import Qwen2ForCausalLM\n",
    "from sentence_transformers import SentenceTransformer\n",
    "from qdrant_client import QdrantClient\n",
    "\n",
    "import uvicorn\n",
    "\n",
    "app = FastAPI()\n",
    "\n",
    "# Initialize SentenceTransformer for embeddings\n",
    "MODEL = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')\n",
    "\n",
    "# Initialize Qdrant client\n",
    "client = QdrantClient(url=\"http://localhost:6333\")\n",
    "\n",
    "# Initialize Qwen2 model for text generation\n",
    "model_name = \"Qwen/Qwen2-0.5B-Chat\"  # Update with the appropriate Qwen model name\n",
    "tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)\n",
    "model = Qwen2ForCausalLM.from_pretrained(model_name, trust_remote_code=True)\n",
    "generator = pipeline(\n",
    "    \"text-generation\",\n",
    "    model=model,\n",
    "    tokenizer=tokenizer,\n",
    "    max_new_tokens=300,  # Allows for longer answers\n",
    "    temperature=0.5,\n",
    "    repetition_penalty=1.3\n",
    ")\n",
    "\n",
    "# Input schema\n",
    "class LLMQuery(BaseModel):\n",
    "    question: str\n",
    "\n",
    "@app.post(\"/llm_query\")\n",
    "def llm_query(query: LLMQuery):\n",
    "    # Step 1: Embed the query question\n",
    "    question_embeddings = MODEL.encode(query.question).tolist()\n",
    "\n",
    "    # Step 2: Search for similar context in Qdrant\n",
    "    search_result = client.search(\n",
    "        collection_name=\"similar_text\",  # Replace with your collection name\n",
    "        query_vector=question_embeddings,\n",
    "        limit=3  # Retrieve the top 1 result\n",
    "    )\n",
    "\n",
    "    # Extract context from Qdrant results\n",
    "    context = \" \".join([item.payload[\"text\"] for item in search_result]) if search_result else \"No relevant context found.\"\n",
    "\n",
    "    # Debugging: Log the context and question\n",
    "    print(f\"Context: {context}\")\n",
    "    print(f\"Question: {query.question}\")\n",
    "\n",
    "    # Step 3: Prepare the prompt for Qwen2\n",
    "    prompt = (\n",
    "        f\"Given the following context, provide a short answer to the question.\\n\\n\"\n",
    "        f\"Context:\\n{context}\\n\\n\"\n",
    "        f\"Question:\\n{query.question}\\n\\n\"\n",
    "        f\"Answer:\"\n",
    "    )\n",
    "\n",
    "    # Step 4: Generate an answer using the Qwen2 model\n",
    "    raw_answer = generator(prompt, return_full_text=False)[0][\"generated_text\"]\n",
    "\n",
    "    # Debugging: Log the raw answer\n",
    "    print(f\"Raw Answer: {raw_answer}\")\n",
    "\n",
    "    # Extract the answer from the model output\n",
    "    clean_answer = raw_answer.strip()\n",
    "\n",
    "    # Step 5: Return the response\n",
    "    response = {\n",
    "        \"question\": query.question,\n",
    "        \"context\": context,\n",
    "        \"answer\": clean_answer or \"No answer generated.\"\n",
    "    }\n",
    "    return JSONResponse(content=response, headers={\"Content-Type\": \"application/json\"})\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    uvicorn.run(app, host=\"0.0.0.0\", port=8000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f1df3658",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
